active_label: 1
data_key: features
image_key: images
labels:
- active: true
  color: white
  name: class 0
- active: true
  color: red
  name: class 1
output_dir: /home/amin/Dropbox/Education/PhD/coding/Python/annotateEZ/output
tile_size: 45
x_size: 30
y_size: 18
